version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - jzucker2
    assignees:
      - jzucker2
    labels:
      - github_actions
  # maintain dependencies for python project
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    reviewers:
      - jzucker2
    assignees:
      - jzucker2
    labels:
      - dependencies
    allow:
      # Allow updates for flask and related packages
      - dependency-name: "Flask*"
      - dependency-name: "SQLAlchemy"
      # allow updates for specific clients
      - dependency-name: "denonavr"
      - dependency-name: "phue"
      - dependency-name: "pyatv"
      - dependency-name: "roku"
      - dependency-name: "wakeonlan"
      - dependency-name: "python-kasa"
      - dependency-name: "pyvesync"
      # other dependencies
      - dependency-name: "requests"
      # running the app
      - dependency-name: "gunicorn"
