version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - jzucker2
    assignees:
      - jzucker2
    labels:
      - github_actions

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"
    reviewers:
      - jzucker2
    assignees:
      - jzucker2
    labels:
      - github_actions

  # maintain dependencies for python project
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
    reviewers:
      - jzucker2
    assignees:
      - jzucker2
    labels:
      - dependencies
    allow:
      # Allow updates for flask and related packages
      - dependency-name: "Flask*"
      - dependency-name: "SQLAlchemy"
      # other dependencies
      - dependency-name: "requests"
      # running the app
      - dependency-name: "gunicorn"
      # monitoring
      - dependency-name: "prometheus*"
      # watch pip itself, just in case
      - dependency-name: "pip"
      # big pain to deal with
      - dependency-name: "cryptography"
