version: '3.7'

services:

  filmstock:
    container_name: filmstock
    build:
      context: .
      dockerfile: Dockerfile
    command: ['sh', 'scripts/test.sh']
    volumes:
      - '.:/filmstock'
    ports:
      - "1915:1915"
    stdin_open: true
    tty: true
